services:
  postgres:
    image: postgres:16
    container_name: people_analytics_postgres
    environment:
      POSTGRES_USER: hr_user
      POSTGRES_PASSWORD: hr_password
      POSTGRES_DB: people_analytics
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hr_user -d people_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: