services:
  postgres:
    image: postgres:16
    container_name: people_analytics_postgres
    env_file:
      - .env.docker
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    container_name: people_analytics_api
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./mlruns:/app/mlruns
    restart: always

  dashboard:
    build: .
    container_name: people_analytics_dashboard
    command: python -m app.dashboard.dash_app
    depends_on:
      - postgres
      - api
    env_file:
      - .env.docker
    ports:
      - "8050:8050"
    volumes:
      - .:/app
      - ./mlruns:/app/mlruns
    restart: always


  nginx:
    image: nginx:latest
    container_name: people_analytics_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - dashboard

volumes:
  postgres_data:


